### PR TITLE
specify appName on the build process

### PR DESCRIPTION
**Pull request by mangas**
the debian package run the app with the title "unknown"

### CODE REVIEW

**Comment by MadLittleMods** [comment]
reference: https://github.com/nwjs/nw-builder#optionsappname

It should be getting picked up from `package.json` as the documentation says :confused:

**Comment by mangas** [comment]
It also says "This will be used to generate a plist file for mac." and on linux there is an application name on the .desktop shortcut but the actual window has "Unknown" as the name, I think it would be worth the test

**Comment by MadLittleMods** [comment]
@mangas Have you made a custom build to ensure this actually solves the problem?

**Comment by mangas** [comment]
I wasn't able to verify, I used a container to run the build process and then I was missing the keys. if you can run the build with the change I'm happy to test it

**Comment by mangas** [comment]
Unfortunately after some testing this doesn't seem to fix the gnome-shell window title

**Pull request closed without merging**
