### PR TITLE
Add the initial packaging metadata to build the gitter snap

### PR DESCRIPTION
**Pull request by come-maiz**

### CODE REVIEW

**Comment by come-maiz** [comment]
As suggested by @MadLittleMods, here is a PR to build a snap.

To try this in ubuntu 16.04:

    $ sudo apt install snapcraft git
    $ git clone https://github.com/elopio/desktop
    $ cd desktop
    $ git checkout snapcraft-deb
    $ snapcraft
    $ sudo snap install *.snap --dangerous --classic
    $ gitter

**Comment by come-maiz** [comment]
ping. Anybody around to review this?

**Comment by MadLittleMods** [comment]
Hey @elopio,

Sorry for the delay. Let's add some instructions to the readme on what needs to updated for further releases and how to push a new snap release.

**Comment by come-maiz** [comment]
@MadLittleMods well, for now making new releases would require to edit the source deb.

That's not nice. Remember that this is just a quick approach so you can take a look at what the store offers. Defining your release pipeline depends a lot on your preferences.

Once the binaries are build from source instead of just repackaging the deb, the cool thing to do is to automate the continuous delivery, so there's nothing to do to get newer releases in the store. We are working on build.snapcraft.io to make this with just a couple of clicks, nothing to document and super simple.

For now, I would suggest you to go to https://dashboard.snapcraft.io/, register it and play a little with the store. I'll talk with my teammates to see if they can help you building the snap from source.

**Comment by MadLittleMods** [comment]
More chat here for reference https://gitter.im/gitterHQ/desktop?at=5901c7c5881b89e1018ebb67

Is there a way to link to a snap? Or is the repository only available via CLI?

**Comment by come-maiz** [comment]
oh great, Martin has already been working on this :D
@MadLittleMods if the snap has a desktop file, it will be installable through the ubuntu software center, in addition to the CLI.

**Pull request merged**
